// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.0
//   protoc               v3.20.3
// source: src/posts.proto

/* eslint-disable */
import { Observable } from "rxjs";

export const protobufPackage = "posts";

export interface FindManyByIdsParams {
  ids: string[];
}

export interface Post {
  id: string;
  content: string;
  createdAt: string;
  authorId: string;
}

export interface FindManyByIdsResponse {
  data: Post[];
}

export interface PostsService {
  findManyByIds(request: FindManyByIdsParams): Observable<FindManyByIdsResponse>;
}
